[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "worker"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
  "httpx==0.28.1",
  "nexuswiki-core",
  "pydantic-settings==2.14.2",
]

[tool.uv.sources]
nexuswiki-core = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/worker"]
